@echo off
>>output.txt (
@echo off
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_AMDExt_RTK.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_AsusExt_AVO_RTK.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_AsusExt_AVO_XPERI4_RTK.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_AsusExt_ICE_RTK.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_AsusExt_RTK.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_AsusExt_XPERI4_RTK.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_HpExt_HSA.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_HPExt_RTKOld.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_LenovoExt_RTK.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_MitacExt_RTK.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_MsiExt_AVO_RTK.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_MsiExt_AVO_V4_RTK_KD.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_MsiExt_CT_RTK.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_MsiExt_RTK.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_MsiExt_RTK_KD.inf"
"R:\GitHub\realtek-universal-audio-driver\signtool\signtool.exe" verify /c "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\hdxrtext.cat" "R:\GitHub\realtek-universal-audio-driver\UAD\Realtek\ExtRtk_8832.1\HDX_WhiteExt_RTK.inf"
)
